apiVersion: v1
kind: Secret
metadata:
  name: console-secret
type: Opaque
data:
  CONSOLE_PBKDF_PASSPHRASE: VGhpc0lzU2FsdDEyMwo=
  CONSOLE_PBKDF_SALT: VGhpc0lzU2FsdDEyMwo=
  CONSOLE_ACCESS_KEY: cjNkaDR0MSFAT0NQ
  CONSOLE_SECRET_KEY: cjNkaDR0MSFAT0NQ
