apiVersion: velero.io/v1
kind: Backup
metadata:
  name: todo
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  defaultVolumesToRestic: true
  hooks: {}
  includedNamespaces:
  - todo
  storageLocation: app-backup-1 
  ttl: 720h0m0s