# https://velero.io/docs/main/api-types/backup/
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: todo
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  #defaultVolumesToRestic: true OADP 1.1
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: false # disable restic
  snapshotMoveData: true
  hooks: {}
  includedNamespaces:
  - todo
  storageLocation: app-backup-1 
  ttl: 720h0m0s