 apiVersion: oadp.openshift.io/v1alpha1
 kind: DataProtectionApplication
 metadata:
   name: app-backup
   namespace: openshift-adp
 spec:
   backupImages: false
   configuration:
     nodeAgent:
       enable: true
       uploaderType: kopia
     velero:
       defaultPlugins:
         - aws
         - openshift 
         - csi
   backupLocations:
     - velero:
         config:
           profile: "default"
           region: REGION # In case of minio, use minio
           s3Url: ENDPOINT 
           insecureSkipTLSVerify: "true"
           s3ForcePathStyle: "true"
         provider: aws
         default: true
         credential:
           key: cloud
           name: cloud-credentials # Default. Can be removed 
         objectStorage:
           bucket: S3_BUCKET
           prefix: todo # Optional

#  apiVersion: oadp.openshift.io/v1alpha1
#  kind: DataProtectionApplication
#  metadata:
#    name: app-backup
#    namespace: openshift-adp
#  spec:
#    backupImages: false
#    configuration:
#      velero:
#        defaultPlugins:
#          - aws
#          - openshift 
#      restic:
#        enable: true # If you don't have CSI then you need to enable restic
#    backupLocations:
#      - velero:
#          config:
#            profile: "default"
#            region: REGION # In case of minio, use minio
#            # In case of Minio, http://minio.minio.svc.cluster.local:80
#            s3Url: ENDPOINT 
#            insecureSkipTLSVerify: "true"
#            s3ForcePathStyle: "true"
#          provider: aws
#          default: true
#          credential:
#            key: cloud
#            name: cloud-credentials # Default. Can be removed 
#          objectStorage:
#            bucket: S3_BUCKET
#            prefix: todo # Optional
