apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: todo
  namespace: openshift-adp
spec:
  defaultVolumesToRestic: true
  schedule: '*/5 * * * *' # Backup every 5 minutes for demo purpose. You may use 0 5 * * *
  template:
    hooks: {}
    includedNamespaces:
    - todo
    storageLocation: app-backup-1 
    defaultVolumesToRestic: true 
    ttl: 720h0m0s
